name: Releases 📦

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: make pack_extensions
      - uses: actions/upload-artifact@v3
        with:
          name: regexper-ng-vsix
          path: regexper-ng*.vsix
